version: '3'

services:
  db:
    image: postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: admin
    container_name: EcommercePrueba
    volumes:      
      - ./postgres:/var/lib/postgresql/data